language: C

install:
  # Prerequisites
  - "sudo apt-get install autopoint libreadline-dev wget texinfo"

# run the tests
script: autoreconf -fvi -Wall && ./configure && make update && (cd doc && make stamp-vti) && make && make check
